
#ifndef CONFIG_H
#define CONFIG_H

#define ASECTIC

#define MAIN_WINDOW_WIDE 800
#define MAIN_WINDOW_HIGH 600

#define CREATE_CLASS_WINDOW_WIDE 500
#define CREATE_CLASS_WINDOW_HIGH 300

#define DELETE_CLASS_WINDOW_WIDE 500
#define DELETE_CLASS_WINDOW_HIGH 300

#define CHANGE_CLASS_WINDOW_WIDE 200
#define CHANGE_CLASS_WINDOW_HIGH 200

#define ADD_STUDENT_WINDOW_WIDE 500
#define ADD_STUDENT_WINDOW_HIGH 300

#define DELETE_STUDENT_WINDOW_WIDE 500
#define DELETE_STUDENT_WINDOW_HIGH 300

#define SHOW_OTHER_ONE_WINDOW_WIDE 350
#define SHOW_OTHER_ONE_WINDOW_HIGH 450

#define MAX_COLUMN_COUNT 6

#endif // CONFIG_H
